### USER CRUD ###

# Obtener todos los usuarios
GET http://localhost:3000/api/users
Accept: application/json

###

# Obtener un usuario por ID
GET http://localhost:3000/api/users/1
Accept: application/json

###

# Crear un nuevo usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "strongpassword",
  "isAdmin": false,
  "profilePhoto": "https://i.postimg.cc/15c4wxR6/frank.jpg",
  "qrCode": "http://localhost:3000/index.html?userId=1"
}

###

# Crear un nuevo usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Gio MR",
  "email": "gio@example.com",
  "password": "strongpassword",
  "isAdmin": false,
  "profilePhoto": "https://i.postimg.cc/bwmJVQtw/gio.jpg",
  "qrCode": "http://localhost:3000/index.html?userId=2"
}

###

# Actualizar un usuario existente
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "name": "John Updated",
  "email": "john.updated@example.com",
  "isAdmin": true
}

###

# Eliminar un usuario
DELETE http://localhost:3000/api/users/1
Accept: application/json

###